/*
 * Oceanengine Open Api
 * 巨量引擎开放平台 Open Api
 *
 * The version of the OpenAPI document: 1.0.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bytedance.ads.examples;

import com.bytedance.ads.ApiException;
import com.bytedance.ads.api.QianchuanReportAdGetV10Api;
import com.bytedance.ads.ApiClient;
import com.bytedance.ads.model.QianchuanReportAdGetV10Filtering;
import com.bytedance.ads.model.QianchuanReportAdGetV10FilteringMarketingGoal;
import com.bytedance.ads.model.QianchuanReportAdGetV10FilteringOrderPlatform;
import com.bytedance.ads.model.QianchuanReportAdGetV10OrderType;
import com.bytedance.ads.model.QianchuanReportAdGetV10Response;
import com.bytedance.ads.model.QianchuanReportAdGetV10TimeGranularity;

import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

// url: https://api.oceanengine.com/open_api/v1.0/qianchuan/report/ad/get/ GET
public class QianchuanReportAdGetV10ApiExample {

    private static final QianchuanReportAdGetV10Api api = new QianchuanReportAdGetV10Api();

    public static void main(String[] args) throws ApiException {
        Long advertiserId = 1753269359988803L;
        String startDate = "2023-12-25";
        String endDate = "2024-01-10";
        List<String> fields = Arrays.asList("stat_cost", "show_cnt", "ctr");
        QianchuanReportAdGetV10Filtering filtering = new QianchuanReportAdGetV10Filtering();
        filtering.setMarketingGoal(QianchuanReportAdGetV10FilteringMarketingGoal.ALL);
        filtering.setOrderPlatform(QianchuanReportAdGetV10FilteringOrderPlatform.QIANCHUAN);
        QianchuanReportAdGetV10TimeGranularity timeGranularity = null;
        String orderField = null;
        QianchuanReportAdGetV10OrderType orderType = null;
        Integer page = null;
        Integer pageSize = null;
        ApiClient apiClient = api.getApiClient();
        apiClient.addDefaultHeader("Access-Token", "15c213fe148dabb5c571484409a50e3597832be0");
        apiClient.setDebugging(true);
        api.setApiClient(apiClient);
        QianchuanReportAdGetV10Response response = api.openApiV10QianchuanReportAdGetGet(advertiserId, startDate, endDate, fields, filtering, timeGranularity, orderField, orderType, page, pageSize);
        System.out.println(response);
        String output = response.toString();
        System.out.println(output);
        writeOutputToFile(output, "output.txt");
    }
    private static void writeOutputToFile(String output, String filePath) {
        try (FileWriter fileWriter = new FileWriter(filePath)) {
            // 将输出写入文件
            fileWriter.write(output);
            System.out.println("输出已成功写入文件: " + filePath);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

}