/*
 * Oceanengine Open Api
 * 巨量引擎开放平台 Open Api
 *
 * The version of the OpenAPI document: 1.0.16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bytedance.ads.examples;

import com.bytedance.ads.ApiException;
import com.bytedance.ads.api.AdCostProtectStatusGetV2Api;
import com.bytedance.ads.ApiClient;
import com.bytedance.ads.model.AdCostProtectStatusGetV2Response;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

// url: https://api.oceanengine.com/open_api/2/ad/cost_protect_status/get/ GET
public class AdCostProtectStatusGetV2ApiExample {

    private static final AdCostProtectStatusGetV2Api api = new AdCostProtectStatusGetV2Api();

    public static void main(String[] args) throws ApiException {
        Long advertiserId = 1753269359988803L; // 注意末尾的 'L'
        List<Long> adIds = new ArrayList<>();
        adIds.add(1787775900116137L); // 注意末尾的 'L'

        ApiClient apiClient = api.getApiClient();
        apiClient.addDefaultHeader("Access-Token", "15c213fe148dabb5c571484409a50e3597832be0");
        apiClient.setDebugging(true);
        api.setApiClient(apiClient);
        AdCostProtectStatusGetV2Response response = api.openApi2AdCostProtectStatusGetGet(advertiserId, adIds);
        System.out.println(response);
    }

}